name: MacOS12
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Disable Spotlight indexing
      run: sudo mdutil -i off -a
    - name: Setup VNC Server (#1)

      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -allowAccessFor -allUsers -privs -all
    - name: Setup VNC server (#2)
      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes 
    - name: Setup VNC server (#3)
      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvncpw -vncpw 254322
    - name: Setup VNC server (#4)
      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent -console
    - name: Setup VNC server (#5)
      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate
    - name: Install ngrok
      run: brew install ngrok/ngrok/ngrok
    - name: Install Teamviewer
      run: brew install --cask teamviewer
    - name: Setup user

      run: source setuser.sh
    - name: Set up ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: ngrok config add-authtoken $NGROK_AUTH_TOKEN
    - name: Run ngrok
      run: ngrok tcp 5900 &
    - name: ngrok is now listening to VNC connections on...
      run: curl http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
